name: "Deploy Strapi Wrangler"

permissions:
  contents: "read"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/strapi-wrangler-deploy.yaml"
      - "packages/strapi/**/*"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

defaults:
  run:
    shell: "bash"

jobs:
  DeployStrapiWrangler:
    runs-on: "ubuntu-24.04"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Deploy Wrangler"
        uses: "cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65" # v3.14.1
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          accountId: "${{ vars.CLOUDFLARE_ACCOUNT_ID }}"
          workingDirectory: "packages/strapi"
          wranglerVersion: "4.26.0"
