name: "Upload Web Versions Wrangler on pull request"

permissions:
  contents: "read"

on:
  workflow_call:
    inputs:
      CLOUDFLARE_ACCOUNT_ID:
        required: true
        type: "string"
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true

defaults:
  run:
    shell: "bash"

jobs:
  UploadWebVersionsWrangler:
    runs-on: "ubuntu-24.04"

    if: "${{ github.actor != 'dependabot[bot]' }}"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install Dependencies"
        working-directory: "packages/web"
        run: "npm install"

      - name: "Build"
        working-directory: "packages/web"
        run: "npm run build"
        env:
          STRAPI_URL: "https://strapi.kaito.tokyo"

      - name: "Deploy Wrangler"
        uses: "cloudflare/wrangler-action@v3"
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          accountId: "${{ inputs.CLOUDFLARE_ACCOUNT_ID }}"
          workingDirectory: "packages/web"
          wranglerVersion: "4.26.0"
          command: "versions upload"
