name: "Pull request"

permissions:
  contents: "read"

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  PrUploadWebVersionsWrangler:
    uses: "./.github/workflows/pr-web-wrangler-versions-upload.yaml"
    permissions:
      contents: "read"
    secrets: "inherit"
    with:
      CLOUDFLARE_ACCOUNT_ID: "${{ vars.CLOUDFLARE_ACCOUNT_ID }}"
