name: "Prettier on push"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: "bash"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Run Prettier"
        run: "npx prettier --check ."
