name: "Push"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"

jobs:
  PushPrettier:
    uses: "./.github/workflows/push-prettier.yaml"

  PushStrapiImageBuild:
    uses: "./.github/workflows/push-strapi-image-build.yaml"
