name: "Push"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref == 'refs/heads/main' }}"

jobs:
  PushPrettier:
    uses: "./.github/workflows/push-prettier.yaml"
    permissions:
      contents: "read"

  PushStrapiImageBuild:
    uses: "./.github/workflows/push-strapi-image-build.yaml"
    permissions:
      contents: "read"
      packages: "write"
