name: "Build Strapi Wrangler on push"

on:
  workflow_call:

permissions:
  contents: "read"

concurrency:
  group: "${{github.workflow}}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/main' }}"

defaults:
  run:
    shell: "bash"

jobs:
  BuildStrapiWrangler:
    runs-on: "ubuntu-latest"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "20"

      - name: "Install dependencies"
        run: "npm ci"

      - name: "Set up Docker Buildx"
        run: |
          docker buildx create --name my-builder --driver docker-container --use
          docker buildx inspect my-builder --bootstrap

      - name: "Build Strapi Docker image"
        run: |
          docker buildx build \
            --tag "registry.cloudflare.com/serverless-kaito-tokyo-strapi-container:latest" \
            --cache-from "type=gha" \
            --cache-to "type=gha,mode=max" \
            --load \
            "./packages/strapi/image"

      - name: "Build Strapi Wrangler"
        working-directory: "./packages/strapi"
        run: "npx wrangler build"
