name: "Deploy Web Wrangler"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/web-wrangler-deploy.yaml"
      - "packages/web/**/*"

jobs:
  DeployWebWrangler:
    runs-on: "ubuntu-latest"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Deploy Wrangler"
        uses: "cloudflare/wrangler-action@v3"
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          accountId: "${{ vars.CLOUDFLARE_ACCOUNT_ID }}"
          workingDirectory: "packages/web"
          wranglerVersion: "4.26.0"
