name: "Deploy Strapi Wrandgler"

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/strapi-wrangler-deploy.yaml"
      - "packages/strapi/**/*"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Deploy Wrangler"
        uses: "cloudflare/wrangler-action@v3"
        with:
          apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          accountId: "${{ vars.CLOUDFLARE_ACCOUNT_ID }}"
          workingDirectory: "packages/strapi"
          wranglerVersion: "4"
